export type YouthProfile = {
  slot: number;
  name: string;
  department: string;
  role: string;
  image: string;
  imageLayout: "landscape" | "portrait";
  imagePosition: string;
  imageFit: "cover" | "contain";
  reflection: string;
};

export const youthProfiles: YouthProfile[] = [
  {
    slot: 1,
    name: "刘洲",
    department: "中国银行益阳市桥北支行",
    role: "行长",
    image: "./people/youth-01.jpg",
    imageLayout: "landscape",
    imagePosition: "50% 50%",
    imageFit: "cover",
    reflection: "作为基层支行青年干部，我深知正确的业绩观，不是追逐短期数据、表面亮点，而是把心放在基层、把事干在实处。基层是干事练兵的一线阵地，我将摒弃急功近利、贪慕虚功的心态，立足岗位深耕一线，扎实做好每一项业务、服务好每一位客户。坚持久久为功，创造经得起检验的实绩，充分展现中行基层青年实干担当的时代风貌。",
  },
  {
    slot: 2,
    name: "张鑫",
    department: "中国银行益阳市赫山支行",
    role: "行长",
    image: "./people/youth-02.jpg",
    imageLayout: "portrait",
    imagePosition: "50% 42%",
    imageFit: "contain",
    reflection: "作为网点行长，要牢固树立正确政绩观，不片面追逐存款、业绩指标。日常抓实网点合规管理、风险防控，统筹服务实体经济与普惠客户。坚持立足基层，重视群众金融服务体验，严守各项内控条例。摒弃短视的经营思维，平衡业务发展和资产质量，带好团队风气，以稳健运营、为民便民、风险可控作为衡量工作实绩的标准。",
  },
  {
    slot: 3,
    name: "曹瑞芳",
    department: "中国银行桃江支行",
    role: "（主任级）综合客户经理",
    image: "./people/youth-03.jpg",
    imageLayout: "landscape",
    imagePosition: "50% 50%",
    imageFit: "cover",
    reflection: "树立正确政绩观，关键在于立足当下、放眼长远，围绕支行未来发展、网点提质增效、员工成长规划、客户服务拓展，想清楚管理层怎么看、怎么办、怎么干。我将沉下心来做打基础、固根本、利长远的务实工作，久久为功、善作善成，以金融为民的初心使命，护航支行高质量稳健发展行稳致远。",
  },
  {
    slot: 4,
    name: "曹莹灿",
    department: "中国银行益阳分行公司金融与投资银行部",
    role: "副主任",
    image: "./people/youth-04.jpg",
    imageLayout: "landscape",
    imagePosition: "50% 50%",
    imageFit: "cover",
    reflection: "作为青年干部，开展授信业务要坚决摒弃急功近利的片面业绩思维，不片面追求信贷投放短期成效，脚踏实地开展贷前调查，客观研判企业经营状况和第一还款来源，严把准入关口，始终恪守合规风控底线，统筹业务发展与风险防范，立足服务实体经济。坚持以拙履职、以诚用权，把工作实绩建立在合规稳健的基础之上，推动信贷业务高质量发展。",
  },
  {
    slot: 5,
    name: "曾倩",
    department: "中国银行益阳分行营业部",
    role: "副主任（公司金融）",
    image: "./people/youth-05.jpg",
    imageLayout: "portrait",
    imagePosition: "50% 38%",
    imageFit: "contain",
    reflection: "身为中行青年，我们正处在干事创业的拔节孕穗期，树立正确业绩观，就是扣好职业生涯的第一粒扣子。面对数字化转型，既要保持敢闯敢干的冲劲，敢于在拓客一线啃硬骨头；更要保持冷思考的定力，敬畏风险、合规操作，不做泡沫业绩的制造者。多听客户心声，多思考如何解决业务痛点，用脚步丈量市场，用专业赢得信任。",
  },
  {
    slot: 6,
    name: "胡望",
    department: "中国银行南县支行",
    role: "副行长",
    image: "./people/youth-06.jpg",
    imageLayout: "portrait",
    imagePosition: "50% 40%",
    imageFit: "contain",
    reflection: "学习正确政绩观后，作为一名县支行营销副行长，我彻底摒弃重投放、轻风控的短视思维。立足县域金融，深耕小微企业信贷，抓实全流程风险管控。不追求短期规模，以资产质量、企业实效衡量工作，严守合规廉洁底线，扎根基层金融一线，以实干实绩扛起青年干部金融担当。",
  },
  {
    slot: 7,
    name: "孙婷婷",
    department: "中国银行益阳市桥北支行",
    role: "副行长（运营内控）",
    image: "./people/youth-07.jpg",
    imageLayout: "portrait",
    imagePosition: "50% 42%",
    imageFit: "contain",
    reflection: "正确政绩观是基层运营管理履职尽责、行稳致远的根本遵循。基层网点衡量发展成效，绝不能片面以营销指标、业务增量作为唯一评判标准，必须坚守合规经营底线。在后续工作中，我将继续坚持业务发展与风险管控双线并行、同频推进、双向提质，以稳健规范的运营保障服务质效提升，为支行高质量稳健发展夯实长效运营根基。",
  },
  {
    slot: 8,
    name: "刘娟",
    department: "中国银行益阳分行综合管理部",
    role: "团委书记",
    image: "./people/youth-12.jpg",
    imageLayout: "portrait",
    imagePosition: "50% 42%",
    imageFit: "contain",
    reflection: "通过学习树立和践行正确政绩观，我深知要摒弃重形式轻实效的思维。办公室工作务求务实严谨，做实办文、办会、办事，不做表面文章；团委工作立足青年实际，扎实开展理论学习、团青活动，拒绝花架子。始终坚持求真务实，严守纪律规矩，把服务大局、服务青年作为出发点，脚踏实地做好各项基础性工作，以实干实绩诠释青年担当，助力全行高质量发展。",
  },
  {
    slot: 9,
    name: "周冰玉",
    department: "中国银行益阳市赫山支行",
    role: "团委副书记",
    image: "./people/youth-09.jpg",
    imageLayout: "landscape",
    imagePosition: "50% 50%",
    imageFit: "cover",
    reflection: "作为一名基层客户经理，我深知要树立正确政绩观，不能一味追求业绩指标。日常工作坚守合规底线，理性开展客户营销，认真做好贷前调查、贷后管理。立足岗位切实帮扶实体经济小微企业，拒绝重短期效益、轻风险管控。端正从业心态，以客户真实需求为先，严守信贷纪律，踏实尽责，把稳健经营、防控风险当作最重要的工作实绩。",
  },
  {
    slot: 10,
    name: "陈嘉妮",
    department: "中国银行益阳市龙洲北路支行",
    role: "团委副书记",
    image: "./people/youth-10.jpg",
    imageLayout: "portrait",
    imagePosition: "50% 42%",
    imageFit: "contain",
    reflection: "作为一名青年银行客户经理，通过学习正确政绩观，我深刻认识到业绩不只是业务规模、客户数量等显性指标。在日常岗位工作中，不能急功近利、片面追求短期业务成效。面对营销拓展，既要主动开拓业务，更要严守信贷合规底线，做实客户调查，把风险防控贯穿业务全流程。坚持立足实体经济真实需求，摒弃重增量轻质量的浮躁心态，把金融服务实效、资产质量稳定作为真正的政绩。",
  },
  {
    slot: 11,
    name: "石晨霞",
    department: "中国银行益阳市资阳支行",
    role: "团委学习委员",
    image: "./people/youth-11.jpg",
    imageLayout: "portrait",
    imagePosition: "50% 40%",
    imageFit: "contain",
    reflection: "作为一名客户经理，通过学习树立正确政绩观，我深刻认识到业绩不能只追求短期指标。工作中坚持合规展业，摒弃重规模、轻质量的片面思维，用心服务客户真实融资需求，防范信贷风险。立足岗位沉下心做实基础业务，兼顾业务发展与风险防控。坚守金融初心，以客户长期稳定发展、资产质量稳健检验工作成效，脚踏实地担当作为。",
  },
  {
    slot: 12,
    name: "陈诗婕",
    department: "中国银行益阳市桃花仑支行",
    role: "团委副书记",
    image: "./people/youth-08.jpg",
    imageLayout: "landscape",
    imagePosition: "50% 50%",
    imageFit: "cover",
    reflection: "作为综合客户经理，我将牢固树立和践行正确政绩观，业务操作方面，不片面追求业务规模、短期业绩，坚持合规展业，把风险防控摆在业务拓展前面；客户营销方面，立足实体经济，做实客户服务，摒弃重营销轻风控的思维。严守信贷纪律，做实贷前贷中贷后全流程管理，脚踏实地做好本职工作，坚守金融初心，实现业务稳健可持续发展。",
  },
];
